<?php

if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array (
        'key' => 'group_5911a71018fsdfdssfds60611122',
        'title' => 'Quiz',
        'fields' => array (
            array (
                'key' => 'field_fdfd432ss879111233',
                'label' => 'Vragen',
                'name' => 'quiz_vragen',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),

            array (
                'key' => 'field_59vcxbv54326542cvcxfgd88',
                'label' => 'Vragen',
                'name' => 'quiz_vragen',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'row',
                'button_label' => 'Voeg een vraag toe',
                'sub_fields' => array (
                    array (
                        'key' => 'field_59654fdasfdsgdfe',
                        'label' => 'Vraag',
                        'name' => 'quiz_vraag',
                        'type' => 'text',
                        'menu_order' => 0,
                        'instructions' => '',
                        'required' => 0,
                        'id' => '',
                        'class' => '',
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_59vcxbv54322cvcxfgd88',
                        'label' => 'Antwoorden',
                        'name' => 'quiz_antwoorden',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array (
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'collapsed' => '',
                        'min' => 0,
                        'max' => 0,
                        'layout' => 'row',
                        'button_label' => 'Voeg antwoord toe',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_59654fdasgd4532fe',
                                'label' => 'Antwoord',
                                'name' => 'quiz_antwoord',
                                'type' => 'text',
                                'menu_order' => 0,
                                'instructions' => '',
                                'required' => 0,
                                'id' => '',
                                'class' => '',
                                'conditional_logic' => 0,
                                'wrapper' => array (
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'maxlength' => '',
                            ),
                        ),
                    ),
                ),
            ),



            array (
                'key' => 'field_fdfd432ss87911rew1233',
                'label' => 'Popup',
                'name' => 'quiz_vragen',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array (
                'key' => 'field_59654fdasgdlkjhgfd4532fe',
                'label' => 'Title',
                'name' => 'quiz_popup_title',
                'type' => 'text',
                'menu_order' => 0,
                'instructions' => '',
                'required' => 0,
                'id' => '',
                'class' => '',
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array (
                'key' => 'fielfdsfsdae87',
                'label' => 'Popup text',
                'name' => 'quiz_popup_text',
                'type' => 'textarea',
                'default_value' => '',
                'placeholder' => '',
                'maxlength' => '',
                'rows' => '',
                'formatting' => 'br',
            ),
            array (
                'key' => 'field_59654fdasgdfdsf76542314532fe',
                'label' => 'Button text',
                'name' => 'quiz_button_text',
                'type' => 'text',
                'menu_order' => 0,
                'instructions' => '',
                'required' => 0,
                'id' => '',
                'class' => '',
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_lfdps314532fe',
                'label' => 'Redirect link',
                'name' => 'quiz_popup_link',
                'type' => 'text',
                'menu_order' => 0,
                'instructions' => '',
                'required' => 0,
                'id' => '',
                'class' => '',
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),



            array (
                'key' => 'field_fdfd432ss8oiuy7911rew12fdsfds33',
                'label' => 'Essentials',
                'name' => 'quiz_achtergrond_tab',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array (
                'key' => 'field_lfdptrtrtr45632fe',
                'label' => 'Contact form shortcode',
                'name' => 'quiz_shorcode',
                'type' => 'text',
                'menu_order' => 0,
                'instructions' => '',
                'required' => 0,
                'id' => '',
                'class' => '',
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_591eb4fa2btrfdse8c',
                'label' => 'Achtergrond',
                'name' => 'quiz_achtergrond',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'return_format' => 'array',
                'min_width' => 0,
                'min_height' => 0,
                'min_size' => 0,
                'max_width' => 0,
                'max_height' => 0,
                'max_size' => 0,
                'mime_types' => '',
            ),


        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'quiz.php',
                ),
            ),
        ),
        'menu_order' => 10,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array (
            1 => 'the_content',
            2 => 'excerpt',
            3 => 'custom_fields',
            4 => 'discussion',
            5 => 'comments',
            6 => 'revisions',
            7 => 'slug',
            8 => 'author',
            9 => 'format',
            10 => 'page_attributes',
            11 => 'featured_image',
            12 => 'categories',
            13 => 'tags',
            0 => 'send-trackbacks',
        ),
        'active' => 1,
        'description' => '',
    ));

endif;